---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: nova-ml-postgresql
  namespace: nova-postgresql
  labels:
    app: nova-postgresql
spec:
  teamId: "ml"
  dockerImage: ${imageRepository}/zalando/spilo-17:4.0-p2
  volume:
    size: 1Gi
    storageClass: ${postgreSqlStorageClass}
  numberOfInstances: 1
  users:
    mluser:
      - superuser
      - createdb
  databases:
    airflow: mluser
    mlflow: mluser
    mlflow_users: mluser
    jupyterhub: mluser
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  enableConnectionPooler: false
  enableReplicaConnectionPooler: false
  enableMasterPoolerLoadBalancer: false
  enableReplicaPoolerLoadBalancer: false
  allowedSourceRanges:
    - 127.0.0.1/32
  postgresql:
    version: "17"
  sidecars:
    - name: "exporter"
      image: "${imageRepository}/prometheuscommunity/postgres-exporter:v0.15.0"
      ports:
        - name: exporter
          containerPort: 9187
          protocol: TCP
      env:
        - name: DATA_SOURCE_URI
          value: ":5432/?sslmode=disable"
        - name: DATA_SOURCE_USER
          valueFrom:
            secretKeyRef:
              name: postgres.nova-ml-postgresql.credentials.postgresql.acid.zalan.do
              key: username
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              name: postgres.nova-ml-postgresql.credentials.postgresql.acid.zalan.do
              key: password
      resources:
        requests:
          cpu: 100m
          memory: 200M
  tls:
    secretName: "nova-postgres-tls"
    certificateFile: "tls.crt"
    privateKeyFile: "tls.key"
    caFile: "ca.crt"
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
  patroni:
    failsafe_mode: false
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    synchronous_mode: false
    synchronous_mode_strict: false
    synchronous_node_count: 1
    maximum_lag_on_failover: 33554432
    pg_hba:
      - local   all             all                             trust
      - local   replication     standby                         trust
      - hostssl replication     standby            all          md5
      - hostssl all             +zalandos          all          pam
      - host    all             all                all          md5
      - hostssl all             all                all          md5
      - host    all             all                ::1/128      md5
  enableShmVolume: true
  spiloRunAsUser: 101
  spiloRunAsGroup: 103
  spiloFSGroup: 103
  additionalVolumes:
    - name: empty
      mountPath: /opt/empty
      targetContainers:
        - all
      volumeSource:
        emptyDir: {}
    - name: ca-cert
      mountPath: /tlsca/ca.crt
      subPath: ca-certificates.pem
      targetContainers:
        - postgres
      volumeSource:
        configMap:
          name: trusted-ca-bundle
---
apiVersion: v1
kind: Service
metadata:
  name: nova-ml-postgresql-svc-metrics-master
  namespace: nova-postgresql
  labels:
    app: nova-postgresql
    spilo-role: master
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  type: ClusterIP
  ports:
    - name: exporter
      port: 9187
      targetPort: exporter
  selector:
    application: spilo
    cluster-name: nova-ml-postgresql
    spilo-role: master
---
apiVersion: v1
kind: Service
metadata:
  name: nova-ml-postgresql-svc-metrics-replica
  namespace: nova-postgresql
  labels:
    app: nova-postgresql
    spilo-role: replica
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  type: ClusterIP
  ports:
    - name: exporter
      port: 9187
      targetPort: exporter
  selector:
    application: spilo
    cluster-name: nova-ml-postgresql
    spilo-role: replica
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nova-ml-postgresql-svcm-master
  namespace: nova-postgresql
  labels:
    app: nova-postgresql
    spilo-role: master
spec:
  endpoints:
    - port: exporter
      interval: 15s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - nova-postgresql
  selector:
    matchLabels:
      app: nova-postgresql
      spilo-role: master
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nova-ml-postgresql-svcm-replica
  namespace: nova-postgresql
  labels:
    app: nova-postgresql
    spilo-role: replica
spec:
  endpoints:
    - port: exporter
      interval: 15s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - nova-postgresql
  selector:
    matchLabels:
      app: nova-postgresql
      spilo-role: replica
