apiVersion: mellanox.com/v1alpha1
kind: NicClusterPolicy
metadata:
  name: nic-cluster-policy
spec:
  ofedDriver:
    image: doca-driver
    repository: ${imageRepository}/nvidia/mellanox
    version: 25.01-0.6.0.0-0
    upgradePolicy:
      autoUpgrade: true
      drain:
        deleteEmptyDir: true
        enable: true
        force: true
        timeoutSeconds: 300
      maxParallelUpgrades: 1
    startupProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 30
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 30

  rdmaSharedDevicePlugin:
    image: k8s-rdma-shared-dev-plugin
    repository: ${imageRepository}/mellanox
    version: v1.5.2
    config: |
      {
        "configList": [
          {
            "resourceName": "rdma_shared_device_a",
            "rdmaHcaMax": 63,
            "selectors": {
              "vendors": ["15b3"],
              "deviceIDs": ["101b"]
            }
          }
        ]
      }

  secondaryNetwork:
    cniPlugins:
      image: plugins
      repository: ${imageRepository}/k8snetworkplumbingwg
      version: v1.5.0
    ipamPlugin:
      image: whereabouts
      repository: ${imageRepository}/k8snetworkplumbingwg
      version: v0.7.0

  nicFeatureDiscovery:
    image: nic-feature-discovery
    repository: ${imageRepository}/mellanox
    version: v0.0.1
