apiVersion: apps.nova-platform.io/v1alpha1
kind: MLInfrastructure
metadata:
  name: nova-ml-infrastructure
  labels:
    app.kubernetes.io/name: nova-apps-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  nvidiaGpuOperator:
    mig:
      enabled: true
      strategy: single
      configRef: "mig_config_from_git"
    timeSlicing:
      enabled: true
      configRef: "ts_config_from_git"
  nvidiaNetworkOperator:
    enabled: false
