{
 "title": "MinIO / Server",
 "description": "MinIO Server Grafana Dashboard - https://min.io/",
 "tags": [ "minio" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(up{job=\"nova-minio-health\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(minio_node_process_starttime_seconds{job=\"nova-minio-health\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total S3 Ingress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (minio_s3_traffic_received_bytes{job=\"nova-minio-health\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_total_bytes{job=\"nova-minio-health\",instance=~\"$instance\"}) by (instance)) - topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=\"nova-minio-health\",instance=~\"$instance\"}) by (instance))",
     "legendFormat": "Used"
    },
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=\"nova-minio-health\",instance=~\"$instance\"}) by (instance)) ",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Data Usage Growth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(minio_cluster_usage_total_bytes{job=\"nova-minio-health\",instance=~\"$instance\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Object Size Distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_objects_size_distribution{job=\"nova-minio-health\",instance=~\"$instance\"}",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Open FDs ",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "minio_node_file_descriptor_open_total{job=\"nova-minio-health\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total S3 Egress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (minio_s3_traffic_sent_bytes{job=\"nova-minio-health\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "targets": [
    {
     "expr": "minio_node_go_routine_total{job=\"nova-minio-health\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Health Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_health_status{job=\"nova-minio-health\",instance=~\"$instance\"}",
     "legendFormat": "Pool: {{pool}} Set: {{set}}"
    }
   ]
  },
  {
   "title": "Total Online/Offline Drives",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_drive_online_total{job=\"nova-minio-health\",instance=~\"$instance\"})",
     "legendFormat": "."
    },
    {
     "expr": "max(minio_cluster_drive_offline_total{job=\"nova-minio-health\",instance=~\"$instance\"})",
     "legendFormat": "."
    }
   ]
  },
  {
   "title": "Number of Buckets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_bucket_total{job=\"nova-minio-health\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "S3 API Ingress Rate ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_s3_traffic_received_bytes{job=\"nova-minio-health\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Data Received [{{instance}}]"
    }
   ]
  },
  {
   "title": "S3 API Egress Rate ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_s3_traffic_sent_bytes{job=\"nova-minio-health\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Data Sent [{{instance}}]"
    }
   ]
  },
  {
   "title": "Total Online Servers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_nodes_online_total{job=\"nova-minio-health\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_usage_object_total{job=\"nova-minio-health\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Time Since Last Heal",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(minio_heal_time_last_activity_nano_seconds{job=\"nova-minio-health\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Time Since Last Scan",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(minio_usage_last_activity_nano_seconds{job=\"nova-minio-health\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "S3 API Request Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (api) (increase(minio_s3_requests_total{job=\"nova-minio-health\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate (4xx)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (api) (increase(minio_s3_requests_4xx_errors_total{job=\"nova-minio-health\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate (5xx)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (api) (increase(minio_s3_requests_5xx_errors_total{job=\"nova-minio-health\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Health Breakdown",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_health_erasure_set_online_drives{job=\"nova-minio-health\",instance=~\"$instance\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Online Drives"
    },
    {
     "expr": "minio_cluster_health_erasure_set_read_quorum{job=\"nova-minio-health\",instance=~\"$instance\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Read Quorum"
    },
    {
     "expr": "minio_cluster_health_erasure_set_write_quorum{job=\"nova-minio-health\",instance=~\"$instance\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Write Quorum"
    },
    {
     "expr": "minio_cluster_health_erasure_set_healing_drives{job=\"nova-minio-health\",instance=~\"$instance\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Healing Drives"
    },
    {
     "expr": "minio_cluster_health_erasure_set_status{job=\"nova-minio-health\",instance=~\"$instance\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Status"
    }
   ]
  },
  {
   "title": "Memory Usage ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_node_process_resident_memory_bytes{job=\"nova-minio-health\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read, Write I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(minio_node_io_rchar_bytes{job=\"nova-minio-health\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Node RChar [{{instance}}]"
    },
    {
     "expr": "rate(minio_node_io_wchar_bytes{job=\"nova-minio-health\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Node WChar [{{instance}}]"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(minio_node_process_cpu_total_seconds{job=\"nova-minio-health\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Internode Traffic",
   "type": "timeseries",
   "description": "Total number of bytes received and sent on MinIO cluster",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(minio_inter_node_traffic_sent_bytes{job=\"nova-minio-health\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Internode Bytes Received [{{instance}}]"
    },
    {
     "expr": "rate(minio_inter_node_traffic_received_bytes{job=\"nova-minio-health\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Internode Bytes Sent [{{instance}}]"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "minio_node_file_descriptor_open_total{job=\"nova-minio-health\",instance=~\"$instance\"}",
     "legendFormat": "Open FDs [{{instance}}]"
    }
   ]
  },
  {
   "title": "Syscalls",
   "type": "graph",
   "description": "Number of online drives per MinIO Server",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(minio_node_syscall_read_total{job=\"nova-minio-health\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Read Syscalls [{{instance}}]"
    },
    {
     "expr": "rate(minio_node_syscall_write_total{job=\"nova-minio-health\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Write Syscalls [{{instance}}]"
    }
   ]
  },
  {
   "title": "Scanned Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(minio_node_scanner_objects_scanned{job=\"nova-minio-health\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "[{{instance}}]"
    }
   ]
  },
  {
   "title": "Scanned Versions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(minio_node_scanner_versions_scanned{job=\"nova-minio-health\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "[{{instance}}]"
    }
   ]
  },
  {
   "title": "Scanned Directories",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(minio_node_scanner_directories_scanned{job=\"nova-minio-health\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "[{{instance}}]"
    }
   ]
  },
  {
   "title": "KMS Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minio_cluster_kms_uptime{job=\"nova-minio-health\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KMS Request 4xx Error Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (increase(minio_cluster_kms_request_error{job=\"nova-minio-health\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KMS Online(1)/Offline(0)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "yaxes": [
    { "format": "bool_on_off" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_kms_online{job=\"nova-minio-health\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bucket Scans Finished",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(minio_node_scanner_bucket_scans_finished{job=\"nova-minio-health\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "[{{instance}}]"
    }
   ]
  },
  {
   "title": "KMS Request 5xx Error Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (increase(minio_cluster_kms_request_failure{job=\"nova-minio-health\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KMS Request Success Rate ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_cluster_kms_request_success{job=\"nova-minio-health\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "KMS Request Success [{{instance}}]"
    }
   ]
  },
  {
   "title": "Bucket Scans Started",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(minio_node_scanner_bucket_scans_started{job=\"nova-minio-health\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "[{{instance}}]"
    }
   ]
  }
 ]
}
{
 "title": "MinIO / Bucket",
 "description": "MinIO Bucket Grafana Dashboard - https://min.io/",
 "tags": [ "minio" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Object Size Distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (bucket,range) (minio_bucket_objects_size_distribution{job=\"nova-minio-health\"})",
     "legendFormat": "{{bucket,range}}"
    }
   ]
  },
  {
   "title": "Object Version Distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (bucket,range) (minio_bucket_objects_version_distribution{job=\"nova-minio-health\"})",
     "legendFormat": "{{bucket,range}}"
    }
   ]
  },
  {
   "title": "TTFB Distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (bucket,le,api) (minio_bucket_requests_ttfb_seconds_distribution{job=\"nova-minio-health\"})",
     "legendFormat": "{{bucket,le,api}}"
    }
   ]
  },
  {
   "title": "S3 API Request 4xx Error Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket,api) (increase(minio_bucket_requests_4xx_errors_total{job=\"nova-minio-health\"}[$__rate_interval]))",
     "legendFormat": "{{bucket,api}}"
    }
   ]
  },
  {
   "title": "Inflight Requests Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket,api) (increase(minio_bucket_requests_inflight_total{job=\"nova-minio-health\"}[$__rate_interval]))",
     "legendFormat": "{{bucket,api}}"
    }
   ]
  },
  {
   "title": "Total Requests Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket,api) (increase(minio_bucket_requests_total{job=\"nova-minio-health\"}[$__rate_interval]))",
     "legendFormat": "{{bucket,api}}"
    }
   ]
  },
  {
   "title": "Total Data Sent Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (rate(minio_bucket_traffic_sent_bytes{job=\"nova-minio-health\"}[$__rate_interval]))",
     "legendFormat": "Data Sent [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Usage Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (rate(minio_bucket_usage_total_bytes{job=\"nova-minio-health\"}[$__rate_interval]))",
     "legendFormat": "Usage [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Objects Increase Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (increase(minio_bucket_usage_object_total{job=\"nova-minio-health\"}[$__rate_interval]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Versions Increase Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (increase(minio_bucket_usage_version_total{job=\"nova-minio-health\"}[$__rate_interval]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Delete Markers Increase Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (increase(minio_bucket_usage_deletemarker_total{job=\"nova-minio-health\"}[$__rate_interval]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Time Elapsed Since Last Scan (nanos)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "minio_usage_last_activity_nano_seconds{job=\"nova-minio-health\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Data Received Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (rate(minio_bucket_traffic_received_bytes{job=\"nova-minio-health\"}[$__rate_interval]))",
     "legendFormat": "Data Received [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Replication Data Received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (minio_bucket_replication_received_bytes{job=\"nova-minio-health\"})",
     "legendFormat": "Data Received [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Replication Data Sent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (minio_bucket_replication_sent_bytes{job=\"nova-minio-health\"})",
     "legendFormat": "Replication Data Sent [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Replication Data Failed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (minio_bucket_replication_total_failed_bytes{job=\"nova-minio-health\"})",
     "legendFormat": "Replication Failed [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Replication Failed Objects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (minio_bucket_replication_total_failed_count{job=\"nova-minio-health\"})",
     "legendFormat": "Replication Failed Objects [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Replicated In Objects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (minio_bucket_replication_received_count{job=\"nova-minio-health\"})",
     "legendFormat": "Replicated In Objects [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Replicated Out Objects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (minio_bucket_replication_sent_count{job=\"nova-minio-health\"})",
     "legendFormat": "Replicated Out Objects [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Last Hour Failed Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (rate(minio_bucket_replication_last_hour_failed_bytes{job=\"nova-minio-health\"}[$__rate_interval]))",
     "legendFormat": "Last Hour Failed Size [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Last Hour Failed Objects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (minio_bucket_replication_last_hour_failed_count{job=\"nova-minio-health\"})",
     "legendFormat": "Last Hour Failed Objects [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Last Minute Failed Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (rate(minio_bucket_replication_last_minute_failed_bytes{job=\"nova-minio-health\"}[$__rate_interval]))",
     "legendFormat": "Last Minute Failed Size [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Last Minute Failed Objects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (minio_bucket_replication_last_minute_failed_count{job=\"nova-minio-health\"})",
     "legendFormat": "Last Minute Failed Objects [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Replication Latency (millis)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (bucket,range,operation) (minio_bucket_replication_latency_ms{job=\"nova-minio-health\"})",
     "legendFormat": "{{bucket,range,operation}}"
    }
   ]
  },
  {
   "title": "Total Proxied Head Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (minio_bucket_replication_proxied_head_requests_total{job=\"nova-minio-health\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Total Failed Proxied Head Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_bucket_replication_proxied_head_requests_failures{job=\"nova-minio-health\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Proxied Put Tag Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (minio_bucket_replication_proxied_put_tagging_requests_total{job=\"nova-minio-health\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Total Failed Proxied Put Tag Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_bucket_replication_proxied_put_tagging_requests_failures{job=\"nova-minio-health\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Proxied Get Tag Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (minio_bucket_replication_proxied_get_tagging_requests_total{job=\"nova-minio-health\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Total Failed Proxied Get Tag Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_bucket_replication_proxied_get_tagging_requests_failures{job=\"nova-minio-health\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Proxied Delete Tag Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (minio_bucket_replication_proxied_delete_tagging_requests_total{job=\"nova-minio-health\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Total Failed Proxied Delete Tag Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_bucket_replication_proxied_delete_tagging_requests_failures{job=\"nova-minio-health\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Proxied Get Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (minio_bucket_replication_proxied_get_requests_total{job=\"nova-minio-health\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Total Failed Proxied Get Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_bucket_replication_proxied_get_requests_failures{job=\"nova-minio-health\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}
{
 "title": "MinIO / Replication",
 "description": "MinIO Replication Grafana Dashboard - https://min.io/",
 "tags": [ "minio" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Avg. Active Workers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_replication_average_active_workers{job=\"nova-minio-health\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg. Link Latency (millis)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (server, endpoint) (minio_cluster_replication_average_link_latency_ms{job=\"nova-minio-health\"})",
     "legendFormat": "{{server,endpoint}}"
    }
   ]
  },
  {
   "title": "Avg. Queued Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_replication_average_queued_bytes{job=\"nova-minio-health\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg. Queued Objects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_replication_average_queued_count{job=\"nova-minio-health\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg. Transfer Rate (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_replication_average_transfer_rate{job=\"nova-minio-health\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Workers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_replication_current_active_workers{job=\"nova-minio-health\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Link Latency (millis)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server,endpoint) (minio_cluster_replication_current_link_latency_ms{job=\"nova-minio-health\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Transfer Rate (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_replication_current_transfer_rate{job=\"nova-minio-health\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last Minute Queued",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_replication_last_minute_queued_bytes{job=\"nova-minio-health\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last Minute Queued Objects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_replication_last_minute_queued_count{job=\"nova-minio-health\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Link Downtime Duration (sec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server,endpoint) (minio_cluster_replication_link_downtime_duration_seconds{job=\"nova-minio-health\"})",
     "legendFormat": "{{server,endpoint}}"
    }
   ]
  },
  {
   "title": "Link Offline Duration (sec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server,endpoint) (minio_cluster_replication_link_offline_duration_seconds{job=\"nova-minio-health\"})",
     "legendFormat": "{{server,endpoint}}"
    }
   ]
  },
  {
   "title": "Max Active Workers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_max_active_workers{job=\"nova-minio-health\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Link Latency (millis)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server,endpoibt) (minio_cluster_replication_max_link_latency_ms{job=\"nova-minio-health\"})",
     "legendFormat": "{{server,endpoint}}"
    }
   ]
  },
  {
   "title": "Max Queued Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_max_queued_bytes{job=\"nova-minio-health\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Queued Objects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_max_queued_count{job=\"nova-minio-health\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Transfer Rate (per sec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_max_transfer_rate{job=\"nova-minio-health\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Backlog (last 5 mins)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_recent_backlog_count{job=\"nova-minio-health\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Link Online/Offline",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server,endpoint) (minio_cluster_replication_link_online{job=\"nova-minio-health\"})",
     "legendFormat": "{{server,endpoint}}"
    }
   ]
  },
  {
   "title": "Total Proxied Head Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_head_requests_total{job=\"nova-minio-health\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Failed Proxied Head Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_head_requests_failures{job=\"nova-minio-health\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Proxied Put Tag Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_put_tagging_requests_total{job=\"nova-minio-health\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Failed Proxied Put Tag Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_put_tagging_requests_failures{job=\"nova-minio-health\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Proxied Get Tag Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_get_tagging_requests_total{job=\"nova-minio-health\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Failed Proxied Get Tag Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_get_tagging_requests_failures{job=\"nova-minio-health\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Proxied Delete Tag Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_delete_tagging_requests_total{job=\"nova-minio-health\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Failed Proxied Delete Tag Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_delete_tagging_requests_failures{job=\"nova-minio-health\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Proxied Get Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_get_requests_total{job=\"nova-minio-health\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Failed Proxied Get Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_get_requests_failures{job=\"nova-minio-health\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}